# Generated by Django 2.2 on 2019-04-11 17:14

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['name'], 'verbose_name': 'Trabajador', 'verbose_name_plural': 'Trabajadores'},
        ),
        migrations.CreateModel(
            name='design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ot', models.CharField(max_length=10, verbose_name='Orden De Trabajo')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('houri', models.TimeField(verbose_name='Hora Inicial')),
                ('hourf', models.TimeField(verbose_name='Hora Final')),
                ('observations', models.TextField(verbose_name='Observaciones')),
                ('gestion', multiselectfield.db.fields.MultiSelectField(choices=[('Serigrafia', 'Serigrafia'), ('Sublimacion', 'Sublimacion'), ('Vinil', 'Vinil'), ('Vinil Imprim', 'Vinil Imprim'), ('Bordado', 'Bordado'), ('Laser', 'Laser'), ('Bosquejo', 'Bosquejo')], max_length=64, verbose_name='Gestion')),
                ('mts', models.CharField(max_length=10, verbose_name='Metros')),
                ('color', multiselectfield.db.fields.MultiSelectField(choices=[('Jersey', 'Jersey'), ('Dryfit', 'Dryfit'), ('Hidrotech', 'Hidrotech'), ('Algodon Subli.', 'Algodon Subli.'), ('Algodon Chino', 'Algodon Chino'), ('Adidas', 'Adidas')], max_length=59, verbose_name='Color')),
                ('time', models.TimeField(verbose_name='Tiempo')),
                ('worker', models.ManyToManyField(to='core.worker', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Diseño',
                'verbose_name_plural': 'Diseños',
                'ordering': ['date'],
            },
        ),
    ]
