# Generated by Django 2.2 on 2019-04-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190411_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='ot',
            field=models.CharField(max_length=10, unique=True, verbose_name='Orden De Trabajo'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
    ]
