# Generated by Django 2.2 on 2019-04-11 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190411_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='time',
        ),
    ]
