# Generated by Django 2.2 on 2019-04-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_design_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='ot',
            field=models.CharField(max_length=10, verbose_name='Orden De Trabajo'),
        ),
    ]
